---
- block:
  - name: Import Grafana GPG signing key
    apt_key:
      url: "https://packages.grafana.com/gpg.key"
      state: present

  - name: Add Grafana repository
    apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      state: present
      update_cache: yes
  when: ansible_pkg_mgr == "apt" and (ansible_architecture == "x86_64" or ansible_architecture == "armv7l")

- block:
  - name: Install Grafana dependencies on armv6l architecture
    apt:
      pkg:
      - adduser 
      - libfontconfig1
  when: ansible_pkg_mgr == "apt" and (ansible_architecture == "armv6l")

- name: Install grafana package
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - grafana
  notify:
    - Restart grafana
  when: ansible_architecture != "armv6l"

- name: Install Grafana on armv6l architecture
  apt:
    deb: https://dl.grafana.com/oss/release/grafana-rpi_7.3.6_armhf.deb
  when: ansible_pkg_mgr == "apt" and (ansible_architecture == "armv6l")

- name: Set base url for nginx proxy
  lineinfile:
    dest: /etc/grafana/grafana.ini
    regexp: "^;?root_url"
    line: "root_url = %(protocol)s://%(domain)s:/{{ grafana_base_url }}"
  when: grafana_base_url is defined
  notify:
    - Restart grafana
