# Usage:
# # ansible-playbook -i "rupia-rpi1," rupia-rpi1.yml -bK
#
# Needs a corresponding .ssh/config entry:
# # Host rupia-rpi1
# # 	 Hostname <IP of RPI>
# # 	 User pi
---
- hosts: all
  become: true
  roles:
    - role: rpi
    - role: nginx-proxy
    - role: influxdb
    - role: grafana
    - role: air-pi
    #- role: homeassistant
    #- role: nodered
    #- role: ser2mqtt
    #- role: ble2mqtt


